### ISSUE TITLE
Please add copyright license to be explicit about its use

### ISSUE THREAD

**Issue by dev-msingh** [bob-fornal/multi-select#1]
I came across your article published on dev.to. It pointed to this repository. Is this code open source or are all rights reserved for this code?
Any Github repository without a license has all rights reserved. Is this intended?

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license#:~:text=If%20a%20repository%20has%20no,permission%20from%20the%20copyright%20holder.

Thank you very much for sharing this cool implementation though.

**Comment by bob-fornal** [comment]
Added

**Comment by dev-msingh** [comment]
> Added

GPLv3 license is a bit restrictive for people working on commercial applications unless its' a library that can be used without modifications, but anyways thank you very much for making it clear.

**Comment by bob-fornal** [comment]
Changed to MIT ... Please suggest other, if you prefer something else.

**Comment by dev-msingh** [comment]
I think MIT license is perfect for this repository. Thank you very much.
